#!/usr/bin/env python3
"""
Generate a focused UML diagram for the order book backend.

This script uses py2puml for class extraction and limits the diagram to the
orderbook package: OrderBook, Broadcaster, and the support the order book needs
inside that package.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import Iterable, List, Optional, Sequence


PROJECT_ROOT = Path(__file__).resolve().parent
ORDERBOOK_PATH = PROJECT_ROOT / "orderbook"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "uml_output"


PLANTUML_STYLE = """skinparam backgroundColor #FFFFFF
skinparam handwritten false
skinparam shadowing false
skinparam linetype ortho
skinparam roundCorner 8
skinparam defaultFontName Helvetica
skinparam class {
  BackgroundColor #F8FAFC
  BorderColor #334155
  ArrowColor #475569
  FontColor #0F172A
  AttributeFontColor #334155
  MethodFontColor #0F766E
}
skinparam package {
  BackgroundColor #ECFDF5
  BorderColor #047857
  FontColor #052E16
}
skinparam note {
  BackgroundColor #FFFBEB
  BorderColor #D97706
  FontColor #451A03
}
title Order Book Backend UML
"""


SUPPORTING_PLANTUML = """
' Focused support objects used by the orderbook package.
class orderbook.engine.OrderBook {
  +load_snapshot(symbol="BTCUSDT", limit=1000)
  +apply_diff(event, strict=True)
  +process_trade(trade)
  +top_levels(side, depth=10)
  +get_best_bid()
  +get_best_ask()
  +ladder_payload(depth=10)
}

class orderbook.broadcaster.Broadcaster {
  +connect(websocket)
  +disconnect(websocket)
  +broadcast(message)
  +start_broadcasting(order_book, paper_engine=None)
}

class "orderbook.metrics" as Metrics <<module>> {
  +calculate_imbalance(bids, asks, depth)
  +calculate_spread(best_bid, best_ask)
  +calculate_midprice(best_bid, best_ask)
  +calculate_microprice(best_bid, best_ask, best_bid_qty, best_ask_qty)
  +calculate_ofi_step(...)
  +calculate_vpin(volume_buckets)
}

class "sortedcontainers.SortedDict" as SortedDict <<external>>
class "collections.deque" as Deque <<external>>
class "fastapi.WebSocket" as WebSocket <<external>>

orderbook.engine.OrderBook *-- SortedDict : bids / asks
orderbook.engine.OrderBook *-- Deque : ofi_window / mid_prices
orderbook.engine.OrderBook ..> Metrics : microstructure metrics
orderbook.broadcaster.Broadcaster o-- WebSocket : active_connections
orderbook.broadcaster.Broadcaster ..> orderbook.engine.OrderBook : ladder_payload(depth=13)

note right of orderbook.engine.OrderBook
Maintains bid/ask depth, Binance update ids,
best bid/ask history for OFI, CVD, and rolling
mid-price state used by ladder_payload().
end note

note right of orderbook.broadcaster.Broadcaster
Accepts FastAPI WebSocket clients and publishes
OrderBook.ladder_payload() every 100ms.
end note
"""


def require_py2puml():
    try:
        from py2puml.py2puml import py2puml
    except ImportError as exc:
        raise SystemExit(
            "py2puml is required to generate this UML diagram.\n"
            "Install it with:\n"
            "  python -m pip install py2puml\n"
            "or reinstall project dependencies with:\n"
            "  python -m pip install -r requirements.txt"
        ) from exc
    return py2puml


def generate_py2puml_lines() -> List[str]:
    py2puml = require_py2puml()
    return list(py2puml(str(ORDERBOOK_PATH), "orderbook"))


def inject_style_and_support(lines: Iterable[str]) -> str:
    cleaned = [line.rstrip() for line in lines if line.strip()]
    body: List[str] = []

    for line in cleaned:
        if line.startswith("@startuml"):
            body.append(line)
            body.extend(PLANTUML_STYLE.rstrip().splitlines())
        elif line.startswith("footer Generated by"):
            continue
        elif line == "@enduml":
            body.extend(SUPPORTING_PLANTUML.rstrip().splitlines())
            body.append("footer Generated by //py2puml// and focused by //UML.py//")
            body.append(line)
        else:
            body.append(line)

    if not body:
        raise RuntimeError("py2puml did not return any PlantUML content.")

    return "\n".join(body) + "\n"


def write_outputs(puml: str, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "orderbook_broadcaster_uml.puml"
    output_path.write_text(puml, encoding="utf-8")
    return output_path


def render_with_plantuml(puml_path: Path, fmt: str) -> Optional[Path]:
    output_path = puml_path.with_suffix(f".{fmt}")
    try:
        subprocess.run(
            ["plantuml", f"-t{fmt}", str(puml_path)],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except FileNotFoundError:
        print("PlantUML CLI is not installed; wrote the .puml source only.")
        return None
    except subprocess.CalledProcessError as exc:
        print(f"PlantUML render failed with exit code {exc.returncode}; wrote the .puml source only.")
        return None

    return output_path if output_path.exists() else None


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a py2puml PlantUML diagram for OrderBook and Broadcaster."
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="Directory for generated UML files. Default: uml_output",
    )
    parser.add_argument(
        "--render",
        choices=("svg", "png"),
        help="Optionally render with the PlantUML CLI if it is installed.",
    )
    args = parser.parse_args(argv)

    if not ORDERBOOK_PATH.exists():
        print(f"Missing orderbook package: {ORDERBOOK_PATH}", file=sys.stderr)
        return 1

    puml = inject_style_and_support(generate_py2puml_lines())
    puml_path = write_outputs(puml, Path(args.output_dir).resolve())

    print(f"Generated PlantUML: {puml_path.relative_to(PROJECT_ROOT)}")
    if args.render:
        rendered = render_with_plantuml(puml_path, args.render)
        if rendered:
            print(f"Rendered {args.render.upper()}: {rendered.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
